Repository codebuddies/dungeonbuddies, pull requests merged in 2018-11, with the labels that each got.

#12 Update README with more details
  README.md
Labels: feedback wanted, ready for review

#20 feat(): update rack
  Gemfile
  Gemfile.lock
Labels: ready for review

#18 Refactor Dice model
  Dockerfile
  Gemfile
  Gemfile.lock
  app/models/DiceRoller.rb
  app/models/dice.rb
  db/schema.rb
  spec/models/dice_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: backend, devops, ready for review

#21 Release 0.0.1
  Dockerfile
  Gemfile
  Gemfile.lock
  app/models/dice.rb
  db/schema.rb
  spec/models/dice_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: in-progress, release
